### ISSUE TITLE
conditional form sections

### ISSUE THREAD

**Issue by pjagielski** [metosin/lomakkeet#1]
Any hints how to use lomakkeet to build conditional form sections (eg. wizard)?
I tried to include some conditions in `:render-fn` but had to put wizard state into a form state and use internal `ch` to transition state which isn't a clean solution:

``` clojure
    [:input {:type "button"
             :value "> next"
             :onClick #(put! ch {:type :change
                                 :ks [:active]
                                 :value (safe-inc (:active value))})}]]))
```

**Comment by Deraen** [comment]
I would perhaps use `{:type :action, :action :next}` and separate action handler instead of depending on how `:change` works. That will require even more code but it is best I can think of for now.

**Comment by pjagielski** [comment]
Sounds good! 
What should I return from `action` callback? Do you have some working example?

**Comment by Deraen** [comment]
Action should return new form-state (or core.async channel which eventually returns new form-state):

``` clj
(defn next-view [form-state evt]
  (update-in form-state [:active] safe-inc))
```

**Comment by pjagielski** [comment]
Nice, thanks!
